### ISSUE TITLE
Add WF API implementation to UV Docker-Compose

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/workflow-component#18]
DoD:
Container should be up and running with UV and WF API and should be able to access UV.

Testing:
Container Runs and exposes data

**Comment by blankdots** [comment]
Docker-compose suggested config (dpus can be omitted):
```
frontend:
  image: tenforce/unified-views-frontend:latest
  ports:
    - "8080:8080"
  volumes_from:
    - shared
  links:
    - mysql:mysql
    - backend:backend
    - virtuoso:virtuoso
dpus:
  image: tenforce/unified-views-add-dpus
  links: 
    - frontend:frontend
shared:
  image: tenforce/unified-views-shared:latest
backend:
  image: tenforce/unified-views-backend:latest
  volumes_from:
    - shared
  links:
    - mysql:mysql
    - virtuoso:virtuoso
mysql:
  image: tenforce/unified-views-mariadb
  volumes:
    - /data/unifiedviews:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=iamroot!
virtuoso:
  image: tenforce/virtuoso:virtuoso-v7.2.0-latest
api:
  image: attxproject/wfapi
  links: 
    - mysql:mysql
```
for additional information on configurations and settings see: https://github.com/ATTX-project/etl/tree/feature-APIdev/wfAPI
