### ISSUE TITLE
Fix UnifiedViews related dependencies in the shared volumes configuration

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/workflow-component#49]
#### Description
The latest UnifiedViews update broke things up with our current configuration. 
#### DoD
Working UnifiedVIews in our ATTX stack.
#### Testing
Feature Tests Work.

**Comment by joasilva** [comment]
@jkesanie @blankdots 
The Github repo for Dockerised UnifiedViews has been forked from the Tenforce repo (https://github.com/tenforce/docker-unified-views) to the the UnifiedViews repo (https://github.com/UnifiedViews/docker-unified-views). But I can't find a "UnifiedViews" repo in docker Hub (the updated UV images are under the Tenforce repo in docker Hub).

**Comment by joasilva** [comment]
@jkesanie @blankdots 
Using the "feat-compact-modular" tag, all Unified Views images seem to work well together. 

New attx-swarm.yml:
```
version: '3'
services:

  mysql:
    image: tenforce/unified-views-mariadb:feat-compact-modular
#    volumes:
#      - /uv-data/mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=iamroot!
    networks:
      - attx
    deploy:
      placement:
        constraints: [node.hostname == attx-swarm-1]

  shared:
    image: tenforce/unified-views-shared:feat-compact-modular
    volumes:
      - shared_config:/config
      - shared_dpu:/unified-views/dpu
      - shared_lib:/unified-views/lib
#      - shared_scripts:/unified-views/scripts
      - shared_logs:/unified-views/logs
    networks:
      - attx
    deploy:
      placement:
        constraints: [node.hostname == attx-swarm-1]

  backend:
    image: tenforce/unified-views-backend:feat-compact-modular
    volumes:
      - shared_config:/config
      - shared_dpu:/unified-views/dpu
      - shared_lib:/unified-views/lib
#      - shared_scripts:/unified-views/scripts
      - shared_logs:/unified-views/logs
    networks:
      - attx
    depends_on:
      - shared
      - mysql
    deploy:
      placement:
        constraints: [node.hostname == attx-swarm-1]

  frontend:
    image: tenforce/unified-views-frontend:latest
    volumes:
      - shared_config:/config
      - shared_dpu:/unified-views/dpu
      - shared_lib:/unified-views/lib
#      - shared_scripts:/unified-views/scripts
      - shared_logs:/unified-views/logs
    ports:
      - 8080:8080
    networks:
      - attx
    depends_on:
      - shared
      - backend
      - mysql
    deploy:
      placement:
        constraints: [node.hostname == attx-swarm-1]

#  uv-dpus:
#    image: tenforce/unified-views-add-dpus:latest
#    networks:
#      - attx
#    depends_on:
#      - mysql
#      - backend
#      - frontend

  attx-dpus:
    image: attxproject/uv-attx-dpus:elag2017
    networks:
      - attx
    depends_on:
      - mysql
      - backend
      - frontend
#      - uv-dpus

  wfapi:
    image: attxproject/wf-api:1.0
    networks:
      - attx
    depends_on:
      - mysql

#   essiren:
#     image: attxproject/essiren:1.0
# #    volumes:
# #      - /attx-data/essiren:/usr/share/elasticsearch/data
#     networks:
#       - attx
#     ports:
#       - 9200:9200
#       - 9300:9300
#     deploy:
#       placement:
#         constraints: [node.hostname == attx-swarm-2]


  es5:
    image: attxproject/attx-es5:1.0
#    volumes:
#      - /attx-data/elasticsearch5:/usr/share/elasticsearch/data
    networks:
      - attx
    ports:
      - 9210:9210
      - 9310:9310
    # deploy:
    #   placement:
    #     constraints: [node.hostname == attx-swarm-2]

  fuseki:
    image: attxproject/attx-fuseki:elag2017
#    volumes:
#      - /attx-data/fuseki:/data/fuseki
    networks:
      - attx
    environment:
      - ADMIN_PASSWORD=pw123
    ports:
      - 3030:3030
    # deploy:
    #   placement:
    #     constraints: [node.hostname == attx-swarm-2]

  gmapi:
    image: attxproject/gm-api:1.2
#    volumes:
#      - /attx-data/gm-api:/app/data
    networks:
      - attx
    depends_on:
      - frontend
      - fuseki
      - essiren
      - elasticsearch5
      - wfapi
    # deploy:
    #   placement:
    #     constraints: [node.hostname == attx-swarm-2]

  demodata:
    image: attxproject/demodata:elag2017
    networks:
      - attx
    ports:
      - 80:80
    volumes:
      - demo_data:/usr/share/nginx/html

networks:
  attx:
    driver: "overlay"

volumes:
  shared_config:
  shared_dpu:
  shared_lib:
#  shared_scripts:
  shared_logs:
  demo_data:
```
