### ISSUE TITLE
Implement UV-Provenance API

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/workflow-component#56]
#### Description
Implement verstion of UV-Provenance API as described in https://github.com/ATTX-project/workflow-component/issues/50#issuecomment-323964801
#### DoD
New Artifact, Documentation (modify the existing one) and Docker Image (modify the existing one)
#### Testing
Unit testing + Peer Review

**Comment by blankdots** [comment]
Testing compose file (the test image will have to be built locally along with the corresponding artifacts): 
```yml
version: '2'
services:
  mysql:
    image: attxproject/unified-views-mariadb:stable-1.2
    ports:
      - 3306:3306
    volumes:
      - ./uv-data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iamroot!

  shared:
    image: attxproject/unified-views-shared:stable-1.2

  backend:
    image: attxproject/unified-views-backend:stable-1.2
    links:
      - mysql:mysql
    volumes_from:
      - mysql
      - shared

  frontend:
    image: attxproject/unified-views-frontend:stable-1.2
    volumes_from:
      - backend
      - shared
    ports:
      - 8080:8080
    depends_on:
      - shared
      - mysql

  attx-dpus:
    image: attxproject/uv-attx-dpus:stable-1.2
    depends_on:
      - mysql
      - backend
  messagebroker:
    image: rabbitmq:3.6.11-management
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '15671:15671'
      - '15672:15672'
      - '25672:25672'
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password
  fuseki:
    image: attxproject/attx-fuseki:1.0
    environment:
      - ADMIN_PASSWORD=pw123
    ports:
      - 3030:3030
  provservice:
    image: test/provapi
    depends_on:
        - messagebroker
        - fuseki
    environment:
        - MHOST=messagebroker
        - GHOST=fuseki
    links:
      - messagebroker:messagebroker
  uvprov:
    image: test/uvprov
    ports:
      - 4301:4301
    depends_on:
      - messagebroker
      - provservice
    environment:
      - MHOST=messagebroker
      - DBHOST=mysql
    links:
      - messagebroker:messagebroker

```
